# Dockerfile.deploy

FROM golang:1.13 as builder

ENV APP_USER app
ENV APP_HOME /go/src/go-postgres-restful-app

RUN groupadd $APP_USER && useradd -m -g $APP_USER -l $APP_USER
RUN mkdir -p $APP_HOME && chown -R $APP_USER:$APP_USER $APP_HOME

WORKDIR $APP_HOME
USER $APP_USER

RUN go get github.com/jinzhu/gorm
RUN go get github.com/gorilla/mux
RUN go get github.com/lib/pq
RUN go get github.com/rs/cors

COPY src/ .
COPY go.mod .
COPY go.sum .

#RUN go mod download
RUN go mod verify
RUN go build -o go-postgres-restful-app

FROM debian:buster

ENV APP_USER app
ENV APP_HOME /go/src/go-postgres-restful-app

RUN groupadd $APP_USER && useradd -m -g $APP_USER -l $APP_USER
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

COPY src/conf/ conf/
COPY src/views/ views/
COPY --chown=0:0 --from=builder $APP_HOME/go-postgres-restful-app $APP_HOME

EXPOSE 8010
USER $APP_USER
CMD ["./go-postgres-restful-app"]
