# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
#    image: postgres
    build: ./db
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: dbUser
      POSTGRES_DB: InfoTestDb
    container_name: testing_pg_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    container_name: testing_pg_db_adminer
